config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/nomad-coe/ARISE:
      branch: main
      repo: https://github.com/nomad-coe/ARISE
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/nomad-coe/ARISE git:
        commands:
        - /usr/bin/env sh .sqa/script.homely-goldenrod-coral.sh
        container: qc.acc_woolly-alizarin-donkey
  QC.Doc:
    repos:
      github.com/nomad-coe/ARISE find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-aqua-barracuda.sh
        container: qc.doc_shabby-flax-duck
      github.com/nomad-coe/ARISE git:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-coral-abyssinian.sh
        container: qc.doc_lousy-amaranth-rottweiler
      github.com/nomad-coe/ARISE markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-brown-mammoth.sh
        container: qc.doc_muzzy-malachite-owl
      github.com/nomad-coe/ARISE restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-burgundy-ocelot.sh
        container: qc.doc_nerdy-mustard-ray
  QC.Lic:
    repos:
      github.com/nomad-coe/ARISE licensee:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-rose-cougar.sh
        container: qc.lic_scaly-cerulean-malamute
  QC.Sec:
    repos:
      github.com/nomad-coe/ARISE bandit:
        commands:
        - /usr/bin/env sh .sqa/script.surly-emerald-gerbil.sh
        container: qc.sec_snappy-vermilion-turtle
  QC.Sty:
    repos:
      github.com/nomad-coe/ARISE flake8:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-olive-bear.sh
        container: qc.sty_smelly-indigo-oyster
      github.com/nomad-coe/ARISE jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-green-turtle.sh
        container: qc.sty_gummy-crimson-crocodile
  QC.Ver:
    repos:
      github.com/nomad-coe/ARISE get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-tangerine-akbash.sh
        container: qc.ver_snappy-red-eel
timeout: 1800
